frontend-location: NG.Host.Frontend
docker:
  - image:  api
    context: .
    file: ./NG.Host.WebApi/Dockerfile
  - image: frontend
    context: ./NG.Host.Frontend
    file: ./NG.Host.Frontend/Dockerfile  
code-analysis-languages:
  -