name: Continuous Release

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  change-validation:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - run: git fetch --prune --unshallow --tags
      - run: |
          latest_tag=$(git describe --tags --abbrev=0)
          current_commit=$(git rev-parse HEAD)
          
          
          if [ -z "$latest_tag" ]; then
            echo "No tags found. Assuming initial release."
            echo "CHANGES=True" >> $GITHUB_OUTPUT
          else
            changes=$(git log --oneline $latest_tag..HEAD)
            if [ -n "$changes" ]; then
              echo "There are new changes for a new release."
              echo "Last tag: $latest_tag"
              echo "Current commit: $current_commit"
              echo "CHANGES=True" >> $GITHUB_OUTPUT
            else
              echo "No new changes found since the last tag: $latest_tag"
              echo "CHANGES=False" >> $GITHUB_OUTPUT
            fi
          fi
  integration:
    if: ${{ needs.change-validation.outputs.CHANGES == 'True' }}
    needs: [ change-validation ]
    permissions:
      pull-requests: write
      actions: read
      contents: read
      security-events: write
    uses: ./.github/workflows/continuous-integration.yml
  
  update_release_draft:
    if: ${{ needs.change-validation.outputs.CHANGES == 'True' }}
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    needs: [ change-validation, integration ]
    steps:
      - uses: release-drafter/release-drafter@v6.0.0
        id: releaser
        with:
          publish: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Set version
        run: |
          cd NG.Host.Frontend
          npm version ${{ steps.releaser.outputs.tag_name }} --git-tag-version false -f --allow-same-version true
      - name: force update major tag
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "Github action"
          git add NG.Host.Frontend/package.json
          git commit -m "Bump package.json version to ${{ steps.releaser.outputs.tag_name }}"
          git tag ${{ steps.releaser.outputs.tag_name }} -f
          git push origin refs/tags/${{ steps.releaser.outputs.tag_name }} -f
    outputs:
      tag: ${{ steps.releaser.outputs.tag_name }}
  deploy:
    if: ${{ needs.change-validation.outputs.CHANGES == 'True' }}
    name: Publish images to package registry
    runs-on: ubuntu-20.04
    needs: [ change-validation, integration, update_release_draft ]
    permissions: write-all
    strategy:
      fail-fast: false
      matrix:
        image:
          - Api
          - Frontend
        include:
          - image: Api
            context: .
            dockerfile: NG.Host.WebApi/Dockerfile
          - image: Frontend
            context: ./NG.Host.Frontend/
            dockerfile: Dockerfile
    steps:
      - uses: actions/checkout@v4
        name: Check out code

      - name: Build and Publish Docker image
        uses: zvfvrv/docker-bpgpr@1.0.2
        with:
          gh_token: ${{ secrets.GITHUB_TOKEN }}
          image_name: ${{ matrix.image }}
          tags: latest, ${{needs.update_release_draft.outputs.tag}}
          path: ${{ matrix.context }}
          dockerfile: ${{ matrix.dockerfile }}