name: Continuous Release

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  contents: read
  
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  change-validation:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - run: git fetch --prune --unshallow --tags
      - name: Check for changes
        id: check
        run: |
          latest_tag=$(git for-each-ref --sort=-taggerdate --format '%(refname:short)' refs/tags | head -n 1)
          tag=${latest_tag:-}
          current_commit=$(git rev-parse HEAD)
          
          
          if [ -z "$latest_tag" ]; then
            echo "No tags found. Assuming initial release."
            echo "CHANGES=True" >> "$GITHUB_OUTPUT"
          else
            changes=$(git log --oneline $tag..HEAD)
            if [ -n "$changes" ]; then
              echo "There are new changes for a new release."
              echo "Last tag: $latest_tag"
              echo "Current commit: $current_commit"
              echo "CHANGES=True" >> "$GITHUB_OUTPUT"
            else
              echo "No new changes found since the last tag: $latest_tag"
              echo "CHANGES=False" >> "$GITHUB_OUTPUT"
            fi
          fi
    outputs: 
      CHANGES: ${{ steps.check.outputs.CHANGES }}
  integration:
    if: ${{ needs.change-validation.outputs.CHANGES == 'True' }}
    needs: [ change-validation ]
    permissions:
      pull-requests: write
      actions: read
      contents: read
      security-events: write
    uses: ./.github/workflows/continuous-integration.yml
  
  create-release:
    name: Create release
    if: ${{ needs.change-validation.outputs.CHANGES == 'True' }}
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    needs: [ change-validation, integration ]
    steps:
      - uses: release-drafter/release-drafter@v6.0.0
        id: releaser
        with:
          publish: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Set version
        run: |
          cd NG.Host.Frontend
          npm version ${{ steps.releaser.outputs.tag_name }} --git-tag-version false -f --allow-same-version true
      - name: force update major tag
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "Github action"
          git add NG.Host.Frontend/package.json
          git commit -m "Bump package.json version to ${{ steps.releaser.outputs.tag_name }}"
          git tag ${{ steps.releaser.outputs.tag_name }} -f
          git push origin refs/tags/${{ steps.releaser.outputs.tag_name }} -f
    outputs:
      tag: ${{ steps.releaser.outputs.tag_name }}
      
      
  deploy:
    if: ${{ needs.change-validation.outputs.CHANGES == 'True' }}
    name: Publish images to package registry
    runs-on: ubuntu-20.04
    needs: [ change-validation, integration, create-release ]
    permissions: write-all
    strategy:
      fail-fast: false
      matrix:
        image:
          - Api
          - Frontend
        include:
          - image: Api
            context: .
            dockerfile: ./NG.Host.WebApi/Dockerfile
          - image: Frontend
            context: ./NG.Host.Frontend
            dockerfile: ./NG.Host.Frontend/Dockerfile
    steps:
      - uses: actions/checkout@v4
        name: Check out code
        
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ${{ matrix.context }}
          push: true
          file: ${{ matrix.dockerfile }}
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/${{ matrix.image }}:${{ needs.create-release.outputs.tag }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/${{ matrix.image }}:latest
          labels: ${{ steps.meta.outputs.labels }}
