name: Release draft

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:  
  draft-release:
    name: Draft release
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Release type
        id: release_type
        run: |
          echo "IS_PRERELEASE=gh pr view ${{ github.ref }}  --json='labels' -q='any(.labels[]; .name == \"beta\")'" >> $GITHUB_ENV
      - uses: release-drafter/release-drafter@v6.0.0
        with:
          prerelease-identifier: 'beta'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
