name: Release draft

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:  
  draft-release:
    name: Draft release
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v6.0.0
        with:
          prerelease-identifier: 'beta'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
